# This is a basic workflow to help you get started with Actions
name: Deploy to heroku by dockerhub

on:
 # push:
#    branches:
 #     - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Creat .env file
        env: 
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
          ARIA2C_SECRET: ${{ secrets.ARIA2C_SECRET }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          RCLONE_DESTINATION: ${{ secrets.RCLONE_DESTINATION }}
        run: |
          cat > .env << EOF
          ARIA2C_SECRET=${ARIA2C_SECRET}
          HEROKU_APP_NAME=${HEROKU_APP_NAME}
          RCLONE_CONFIG='${RCLONE_CONFIG}'
          RCLONE_DESTINATION=${RCLONE_DESTINATION}
          EOF
          cat .env
          
      - name: "Login to docker hub"     
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build docker image"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.HEROKU_APP_NAME }}:latest
      
      - name: " make new docker file"
        env:
         HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }} 
        run: |
         rm *
         cat > Dockerfile << EOF
         FROM ${HEROKU_APP_NAME}:latest
         ENV PORT=8080
         EXPOSE 8080
         CMD ["bash", "start.sh"]
         EOF
         cat Dockerfile
         
      - uses: akhileshns/heroku-deploy@v3.6.8  # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: master
          usedocker: true
         
